contact_links:
    - name: Just a question?
      url: https://hrzn.link/discord
      about: Talk to us in the Discord if it's just a question.
    - name: Found a vulnerability?
      url: https://hrzn.link/vulnerability
      about: Also refer to our SECURITY.md file, for more detailed advice.
